name: AVPlayerExample
options:
  minimumXcodeGenVersion: 2.38.0
packages:
  HLSCache:
    path: ../..
  Get:
    url: https://github.com/kean/Get.git
    from: 2.0.0
  Pulse:
    url: https://github.com/kean/Pulse.git
    from: 5.0.0
settings:
  base:
    SWIFT_VERSION: 6.0
    DEVELOPMENT_TEAM: ""
    CODE_SIGN_STYLE: Automatic
    TARGETED_DEVICE_FAMILY: "1,2"
    IPHONEOS_DEPLOYMENT_TARGET: 15.0
targets:
  AVPlayerExample:
    type: application
    platform: iOS
    deploymentTarget: "15.0"
    sources:
      - path: AVPlayerExampleApp
    dependencies:
      - package: HLSCache
        product: HLSCache
      - package: Get
        product: Get
      - package: Pulse
        product: Pulse
      - package: Pulse
        product: PulseUI
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.example.AVPlayerExample
        GENERATE_INFOPLIST_FILE: NO
        INFOPLIST_FILE: AVPlayerExampleApp/Info.plist
schemes:
  AVPlayerExample:
    build:
      targets:
        AVPlayerExample: all
    run:
      config: Debug
